query GetTokens($tokenType: [TokenType!], $limit: Int, $sortBy: OrderBy, $_eq: Identity, $_in: [TokenType!], $blockchain: TokenBlockchain!, $limit: Int, $lastUpdatedTimestamp: OrderBy, $_eq1: Identity, $_in1: [TokenType!], $blockchain1: TokenBlockchain!, $lastUpdatedTimestamp1: OrderBy, $_eq2: Identity, $_in2: [TokenType!], $blockchain2: TokenBlockchain!, $limit1: Int, $lastUpdatedTimestamp2: OrderBy, $_eq3: Identity, $_in3: [TokenType!], $blockchain3: TokenBlockchain!, $lastUpdatedTimestamp3: OrderBy, $_eq4: Identity, $_in4: [TokenType!], $blockchain4: TokenBlockchain!, $limit2: Int, $lastUpdatedTimestamp4: OrderBy, $_eq5: Identity, $_in5: [TokenType!], $blockchain5: TokenBlockchain!, $lastUpdatedTimestamp5: OrderBy) {
  ethereum: TokenBalances(
    input: {filter: {owner: {_eq: $_eq}, tokenType: {_in: $_in}}, blockchain: $blockchain, limit: $limit, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp}}
  ) {
    TokenBalance {
      blockchain
      tokenAddress
      tokenType
      tokenNfts {
        tokenId
        contentValue {
          image {
            medium
          }
        }
        erc6551Accounts {
          address {
            addresses
            tokenBalances {
              tokenAddress
              tokenId
              tokenNfts {
                contentValue {
                  image {
                    medium
                  }
                }
              }
            }
          }
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
        tokenBalances(
          input: {filter: {owner: {_eq: $_eq1}, tokenType: {_in: $_in1}}, blockchain: $blockchain1, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp1}}
        ) {
          amount
          tokenType
          blockchain
          tokenAddress
          formattedAmount
          tokenId
          tokenAddress
          owner {
            addresses
          }
          tokenNfts {
            tokenId
            contentValue {
              image {
                medium
              }
            }
            erc6551Accounts {
              address {
                addresses
                tokenBalances {
                  tokenAddress
                  tokenId
                  tokenNfts {
                    contentValue {
                      image {
                        medium
                      }
                    }
                  }
                }
              }
            }
          }
          token {
            isSpam
            name
            symbol
            logo {
              small
            }
            projectDetails {
              imageUrl
            }
          }
        }
      }
    }
  }
  base: TokenBalances(
    input: {filter: {owner: {_eq: $_eq2}, tokenType: {_in: $_in2}}, blockchain: $blockchain2, limit: $limit1, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp2}}
  ) {
    TokenBalance {
      blockchain
      tokenAddress
      tokenType
      tokenNfts {
        tokenId
        contentValue {
          image {
            medium
          }
        }
        erc6551Accounts {
          address {
            addresses
            tokenBalances {
              tokenAddress
              tokenId
              tokenNfts {
                contentValue {
                  image {
                    medium
                  }
                }
              }
            }
          }
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
        tokenBalances(
          input: {filter: {owner: {_eq: $_eq3}, tokenType: {_in: $_in3}}, blockchain: $blockchain3, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp3}}
        ) {
          amount
          tokenType
          blockchain
          tokenAddress
          formattedAmount
          tokenId
          tokenAddress
          owner {
            addresses
          }
          tokenNfts {
            tokenId
            contentValue {
              image {
                medium
              }
            }
            erc6551Accounts {
              address {
                addresses
                tokenBalances {
                  tokenAddress
                  tokenId
                  tokenNfts {
                    contentValue {
                      image {
                        medium
                      }
                    }
                  }
                }
              }
            }
          }
          token {
            isSpam
            name
            symbol
            logo {
              small
            }
            projectDetails {
              imageUrl
            }
          }
        }
      }
    }
  }
  polygon: TokenBalances(
    input: {filter: {owner: {_eq: $_eq4}, tokenType: {_in: $_in4}}, blockchain: $blockchain4, limit: $limit2, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp4}}
  ) {
    TokenBalance {
      blockchain
      tokenAddress
      tokenType
      tokenNfts {
        tokenId
        contentValue {
          image {
            medium
          }
        }
        erc6551Accounts {
          address {
            addresses
            tokenBalances {
              tokenAddress
              tokenId
              tokenNfts {
                contentValue {
                  image {
                    medium
                  }
                }
              }
            }
          }
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
      }
      token {
        isSpam
        name
        symbol
        logo {
          small
        }
        projectDetails {
          imageUrl
        }
        tokenBalances(
          input: {filter: {owner: {_eq: $_eq5}, tokenType: {_in: $_in5}}, blockchain: $blockchain5, order: {lastUpdatedTimestamp: $lastUpdatedTimestamp5}}
        ) {
          amount
          tokenType
          blockchain
          tokenAddress
          formattedAmount
          tokenId
          tokenAddress
          owner {
            addresses
          }
          tokenNfts {
            tokenId
            contentValue {
              image {
                medium
              }
            }
            erc6551Accounts {
              address {
                addresses
                tokenBalances {
                  tokenAddress
                  tokenId
                  tokenNfts {
                    contentValue {
                      image {
                        medium
                      }
                    }
                  }
                }
              }
            }
          }
          token {
            isSpam
            name
            symbol
            logo {
              small
            }
            projectDetails {
              imageUrl
            }
          }
        }
      }
    }
  }
}